<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Terms of Service - Invoice System</title>
    <?php include 'css.php'?>
</head>
<body style="background-color: #f8f9fa; font-family: Arial, sans-serif;">
    <?php include 'welcome_topbar.php'?>

    <div class="container mt-5">

        <div class="text-center mb-4">
                <h1 class="display-4"  style="color: #333;">Terms of Service</h1>
                <p>Welcome to <strong>[Your Company Name]</strong> ("Company", "We", "Us", or "Our"). These Terms of Service ("Terms") govern your use of our multi-tenant invoice system ("Service"). By accessing or using the Service, you agree to be bound by these Terms.</p>
                <p class="last-updated">Last Updated: November 6, 2024</p>
        </div>

        

        <div class="section bg-white p-4 rounded shadow-sm mb-4">
            <h2 style="color: #007bff;">1. Introduction</h2>
            <p>These Terms are legally binding for your organization ("Tenant") when accessing the Service. The Service is designed to manage invoices and related services, and it is available to multiple organizations ("Tenants") using the same platform.</p>
        </div>
    
        <div class="section bg-white p-4 rounded shadow-sm mb-4">
            <h2 style="color: #007bff;">2. Interpretation and Definitions</h2>
            <p><strong>Interpretation</strong><br>
            Capitalized terms have the meanings defined below, whether used in singular or plural.</p>

            <p><strong>Definitions</strong></p>
            <ul>
                <li><strong>"Tenant"</strong>: A registered organization or business using the platform, including all users, data, and invoices.</li>
                <li><strong>"User"</strong>: Any individual or entity accessing the platform on behalf of a Tenant.</li>
                <li><strong>"Content"</strong>: Data uploaded or generated by You or Your users (e.g., invoices, transactions, documents).</li>
                <li><strong>"Account"</strong>: A user or tenant profile created upon registration, including all associated data.</li>
                <li><strong>"Affiliate"</strong>: An entity controlling or controlled by a party, owning 50% or more of the shares or equity interest.</li>
                <li><strong>"Company"</strong>: The service provider of the Invoice System platform, or the organization using the system as a tenant.</li>
                <li><strong>"Country"</strong>: Refers to [___COMPANY_COUNTRY___].</li>
                <li><strong>"Device"</strong>: Any device (e.g., computer, cellphone, tablet) that can access the Service.</li>
                <li><strong>"Feedback"</strong>: Suggestions or feedback about the Service’s features or performance.</li>
                <li><strong>"Service"</strong>: The Invoice System platform provided through the Website.</li>
                <li><strong>"Terms of Service"</strong>: These Terms of Service, forming the entire agreement between You and the Company.</li>
                <li><strong>"Third-party Social Media Service"</strong>: External services or content displayed by the Service, provided by third parties.</li>
                <li><strong>"Website"</strong>: [___WEBSITE_NAME___], accessible at [___WEBSITE_URL___].</li>
                <li><strong>"You"</strong>: The individual or entity accessing or using the Service on behalf of a Tenant.</li>
            </ul>
        </div>

        <div class="section bg-white p-4 rounded shadow-sm mb-4">
            <h2 style="color: #007bff;">3. Company Information</h2>
                <p>The Company provides a multi-tenant invoice system where each organization operates in a secure, isolated environment, with dedicated resources while sharing the same platform. Each "Tenant" has its own business operations, data, and configurations.</p>
        </div>

        <div class="section bg-white p-4 rounded shadow-sm mb-4">
            <h2 style="color: #007bff;">4. User Accounts</h2>
            <strong>Account Creation</strong>
            <p>To use the Service, you must register an account by providing accurate and complete information about your organization. You must maintain up-to-date details to ensure your account remains active.</p>
            <strong>Tenant-Specific Accounts</strong>
            <p>Each organization is considered a separate tenant. Your account will be tied to a specific tenant and will have its own set of data, invoices, and configurations distinct from other tenants using the platform.</p>
            
        </div>

        <div class="section bg-white p-4 rounded shadow-sm mb-4">
            <h2 style="color: #007bff;">5. Usage of Service</h2>
                <p>As a Tenant, you and your users may use the Service for invoicing and related tasks, subject to limitations such as storage and processing limits defined in your plan. You agree to use the Service in compliance with applicable laws and our policies.</p>
        </div>

        <div class="section bg-white p-4 rounded shadow-sm mb-4">
            <h2 style="color: #007bff;">6. Tenant Data</h2>
                <p>Your data (invoices, transaction records, user information) is owned by you and remains confidential. We take reasonable steps to protect your data but make no guarantees regarding the absolute security of data stored within the platform. You are responsible for ensuring the accuracy and integrity of your data.</p>
        </div>
        <div class="section bg-white p-4 rounded shadow-sm mb-4">
            <h2 style="color: #007bff;">7. Payment and Billing</h2>
                <p>By using the Service, you agree to pay the applicable fees as per the plan you select. Payment is required in advance, and the Service may be suspended for failure to pay any outstanding charges. You are responsible for maintaining accurate billing information.</p>
        </div>
        <div class="section bg-white p-4 rounded shadow-sm mb-4">
            <h2 style="color: #007bff;">8. Termination and Suspension</h2>
                <p>We reserve the right to suspend or terminate your access to the Service if you violate these Terms or if your account is inactive for an extended period. Upon termination, your data may be deleted, subject to our data retention policy.</p>
        </div>
        <div class="section bg-white p-4 rounded shadow-sm mb-4">
            <h2 style="color: #007bff;">9. Limitation of Liability</h2>
                <p>The Company is not responsible for any damages, including loss of data, due to the use of the Service. Our liability is limited to the amount paid by you for the Service in the previous month or year, as applicable.</p>
        </div>
        <div class="section bg-white p-4 rounded shadow-sm mb-4">
            <h2 style="color: #007bff;">10. Modifications to Terms</h2>
                <p>We may update or modify these Terms from time to time. You will be notified of significant changes, and by continuing to use the Service, you agree to the updated Terms.</p>
        </div>
        <div class="section bg-white p-4 rounded shadow-sm mb-4">
            <h2 style="color: #007bff;">11. Governing Law</h2>
                <p>These Terms will be governed by the laws of [Your Jurisdiction], without regard to conflict of law principles.</p>
        </div>>

        <div class="section bg-white p-4 rounded shadow-sm mb-4">
            <h2 style="color: #007bff;">3. Acknowledgment</h2>
            <p>These Terms of Service govern Your use of the Service and outline the rights and obligations of all users.</p>
            <p>Your access to and use of the Service is conditioned upon Your acceptance of and compliance with these Terms. These Terms apply to all visitors, users, and others who access the Service.</p>
            <p>By accessing or using the Service, You agree to be bound by these Terms. If You disagree with any part, You may not use the Service.</p>
            <p>You confirm that You are over the age of 18, as the Service is not available to individuals under 18.</p>
            <p>Your use of the Service is also subject to the Company’s Privacy Policy, which governs the collection, use, and disclosure of Your personal information. Please review the Privacy Policy carefully before using the Service.</p>
        </div>

        <div class="section bg-white p-4 rounded shadow-sm mb-4">
            <h2 style="color: #007bff;">4. User Accounts</h2>
            <p>When creating an account, You must provide accurate, complete, and current information. Failure to do so may result in account termination.</p>
            <p>You are responsible for safeguarding Your password and any activities under Your account, whether on Our Service or through Third-Party Social Media Services.</p>
            <p>You agree not to share Your password with third parties. Notify Us immediately if You become aware of any security breaches or unauthorized account use.</p>
            <p>Your username must not infringe on another person or entity’s rights, be misleading, or be offensive in any way.</p>
        </div>

        <div class="section bg-white p-4 rounded shadow-sm mb-4">
            <h2 style="color: #007bff;">5. Content</h2>
            <p><strong>Your Right to Post Content</strong></p>
            <p>You are responsible for the content you post on the Service, including its legality and appropriateness. By posting content, you grant us the right to use, modify, display, reproduce, and distribute it on the Service, while retaining your ownership rights. This license allows us to share your content with other users under these Terms.</p>
            <p>You warrant that: (i) you own or have the right to use the content you post, and (ii) posting your content does not violate any rights, including privacy or copyright, of others.</p>

            <p><strong>Content Restrictions</strong></p>
            <p>You are solely responsible for the content under your account. You agree not to post any content that is unlawful, offensive, threatening, defamatory, obscene, or otherwise objectionable. Examples of prohibited content include:</p>
            <ul>
                <li>Unlawful or promoting unlawful activity.</li>
                <li>Defamatory, discriminatory, or harmful content related to protected groups.</li>
                <li>Spam, unsolicited advertising, or other unauthorized solicitations.</li>
                <li>Content containing viruses, malware, or other harmful software.</li>
                <li>Infringing on any third-party intellectual property rights.</li>
                <li>Impersonating others, including the Company and its representatives.</li>
                <li>Violating privacy or providing false information.</li>
            </ul>
            <p>The Company reserves the right to remove any content that violates these Terms. We may also limit or revoke access to the Service for users posting inappropriate content. Since we cannot control all content, you use the Service at your own risk and agree that the Company is not liable for any offensive or harmful content you encounter.</p>
        </div>

        <div class="section bg-white p-4 rounded shadow-sm mb-4">
            <h2 style="color: #007bff;">6. Content Backups</h2>
            <p>While regular backups of Content are made, the Company does not guarantee against data loss or corruption.</p>
            <p>Backup issues may occur if the content is already corrupted before being backed up or if changes happen during the backup process.</p>
            <p>The Company will provide support to troubleshoot backup issues, but you acknowledge that the Company is not liable for any issues related to content integrity or failure to restore content to a usable state.</p>
            <p>You are responsible for maintaining an independent, complete, and accurate copy of your content outside of the Service.</p>
        </div>

        <div class="section bg-white p-4 rounded shadow-sm mb-4">
            <h2 style="color: #007bff;">7. Copyright Policy</h2>
            
            <p><strong>Intellectual Property Infringement</strong></p>
            <p>We respect intellectual property rights. If you believe that content on our Service infringes your copyright or other intellectual property rights, please notify our copyright agent via email at [___COPYRIGHT_AGENT_CONTACT_EMAIL___] with a detailed description of the alleged infringement.</p>
            <p>Misrepresentation of copyright infringement may result in accountability for damages, including legal costs.</p>
            
            <p><strong>DMCA Notice and Procedure</strong></p>
            <p>To submit a DMCA notice, provide our Copyright Agent with the following written information:</p>
            <ul>
                <li>Your signature or an authorized representative's signature.</li>
                <li>A description of the copyrighted work and its URL or a copy of it.</li>
                <li>The location of the allegedly infringing content on our Service.</li>
                <li>Your contact details.</li>
                <li>A statement of good faith belief that the disputed use is not authorized.</li>
                <li>A statement under penalty of perjury that the information is accurate and that you are the copyright owner or authorized to act on their behalf.</li>
            </ul>
            <p>Upon receipt, the Company may remove the disputed content at its discretion.</p>
            
            <p><strong>Intellectual Property</strong></p>
            <p>Our Service and its original content, features, and functionality remain the exclusive property of the Company and its licensors. The Service is protected by copyright and trademark laws.</p>
            <p>Our trademarks and trade dress may not be used without our prior written consent.</p>
            
            <p><strong>Your Feedback</strong></p>
            <p>Any feedback you provide will be assigned to the Company. If this assignment is ineffective, you grant the Company a non-exclusive, worldwide, irrevocable, royalty-free license to use your feedback without restriction.</p>
            
            <p><strong>Links to Other Websites</strong></p>
            <p>Our Service may link to third-party websites, but we are not responsible for their content, privacy policies, or practices. We advise you to review their terms and policies.</p>
            
            <p><strong>Termination</strong></p>
            <p>We may terminate or suspend your account immediately for any reason, including a breach of these Terms. Your right to use the Service will cease immediately upon termination.</p>
            
            <p><strong>Limitation of Liability</strong></p>
            <p>Our liability is limited to the amount you have paid for the Service or $100 USD, whichever is greater. We are not liable for any incidental, indirect, or consequential damages, including loss of data, profits, or personal injury, arising out of your use of the Service.</p>
            <p>Some jurisdictions may not allow the exclusion of certain warranties or damages, so these limitations may not apply to you.</p>
        </div>

        <div class="section bg-white p-4 rounded shadow-sm mb-4">
            <h2 style="color: #007bff;">8. "AS IS" and "AS AVAILABLE" Disclaimer</h2>
            <p>The Service is provided to You "AS IS" and "AS AVAILABLE" and with all faults and defects without warranty of any kind. To the maximum extent permitted under applicable law, the Company, on its own behalf and on behalf of its Affiliates and its and their respective licensors and service providers, expressly disclaims all warranties, whether express, implied, statutory or otherwise, with respect to the Service, including all implied warranties of merchantability, fitness for a particular purpose, title and non-infringement, and warranties that may arise out of course of dealing, course of performance, usage or trade practice. Without limitation to the foregoing, the Company provides no warranty or undertaking, and makes no representation of any kind that the Service will meet Your requirements, achieve any intended results, be compatible or work with any other software, applications, systems or services, operate without interruption, meet any performance or reliability standards or be error free or that any errors or defects can or will be corrected.</p>
            <p>Without limiting the foregoing, neither the Company nor any of the company's provider makes any representation or warranty of any kind, express or implied: (i) as to the operation or availability of the Service, or the information, content, and materials or products included thereon; (ii) that the Service will be uninterrupted or error-free; (iii) as to the accuracy, reliability, or currency of any information or content provided through the Service; or (iv) that the Service, its servers, the content, or e-mails sent from or on behalf of the Company are free of viruses, scripts, trojan horses, worms, malware, timebombs or other harmful components.</p>
            <p>Some jurisdictions do not allow the exclusion of certain types of warranties or limitations on applicable statutory rights of a consumer, so some or all of the above exclusions and limitations may not apply to You. But in such a case the exclusions and limitations set forth in this section shall be applied to the greatest extent enforceable under applicable law.</p>
            <p><strong>Governing Law</strong></p>
            <p>The laws of the Country, excluding its conflicts of law rules, shall govern this Terms and Your use of the Service. Your use of the Application may also be subject to other local, state, national, or international laws.</p>
            <p><strong>Disputes Resolution</strong></p>
            <p>If You have any concern or dispute about the Service, You agree to first try to resolve the dispute informally by contacting the Company.</p>
            <p><strong>For European Union (EU) Users</strong></p>
            <p>If You are a European Union consumer, you will benefit from any mandatory provisions of the law of the country in which you are resident in.</p>
            <p><strong>United States Legal Compliance</strong></p>
            <p>You represent and warrant that (i) You are not located in a country that is subject to the United States government embargo, or that has been designated by the United States government as a "terrorist supporting" country, and (ii) You are not listed on any United States government list of prohibited or restricted parties.</p>
            <p><strong>Severability and Waiver</strong></p>
            <p><strong>Severability</strong></p>
            <p>If any provision of these Terms is held to be unenforceable or invalid, such provision will be changed and interpreted to accomplish the objectives of such provision to the greatest extent possible under applicable law and the remaining provisions will continue in full force and effect.</p>
            <p><strong>Waiver</strong></p>
            <p>Except as provided herein, the failure to exercise a right or to require performance of an obligation under these Terms shall not effect a party's ability to exercise such right or require such performance at any time thereafter nor shall be the waiver of a breach constitute a waiver of any subsequent breach.</p>
            <p><strong>Translation Interpretation</strong></p>
            <p>These Terms and Conditions may have been translated if We have made them available to You on our Service.<br />
                You agree that the original English text shall prevail in the case of a dispute.</p>
            <p><strong>Changes to These Terms and Conditions</strong></p>
            <p>We reserve the right, at Our sole discretion, to modify or replace these Terms at any time. If a revision is material We will make reasonable efforts to provide at least 30 days' notice prior to any new terms taking effect. What constitutes a material change will be determined at Our sole discretion.</p>
            <p>By continuing to access or use Our Service after those revisions become effective, You agree to be bound by the revised terms. If You do not agree to the new terms, in whole or in part, please stop using the website and the Service.</p>
        </div>


        <div class="section bg-white p-4 rounded shadow-sm mb-4">
            <h2 style="color: #007bff;">9. Contact Us</h2>
            <p>If you have any questions about this Privacy Policy, please contact us at:</p>
            <div class="contact-info mt-3">
                <p>
                    <i class="fas fa-envelope me-2"></i> 
                    <a href="mailto:privacy@invoicesystem.com" style="text-decoration: none;">info@invoicesystem.com</a>
                </p>
                <p>
                    <i class="fas fa-phone me-2"></i> 
                    <a href="tel:+254796335895" style="text-decoration: none;">+1 (555) 123-4567</a>
                </p>
                <p>
                    <i class="fas fa-map-marker-alt me-2"></i>
                    <a href="https://www.google.com/maps/search/?api=1&query=123+Business+Avenue,+New+York,+NY+10001" target="_blank" style="text-decoration: none;">
                        123 Business Avenue, New York, NY 10001
                    </a>
                </p>
            </div>
        </div>

    </div>

    <?php include 'welcome_footer.php'?>
</body>
</html>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Terms of Service</title>
    <link rel="stylesheet" href="styles.css"> <!-- Link to your CSS stylesheet -->
</head>
<body>
    <div class="container">
        <header>
            <h1>Terms of Service</h1>
        </header>
        
        <section class="terms-content">
        </section>

        <section class="agreement">
            <form action="[Your Form Action URL]" method="POST">
                <p>
                    <label for="accept-terms">
                        <input type="checkbox" id="accept-terms" name="accept-terms" required> 
                        I have read and agree to the <a href="#terms-content" target="_self">Terms of Service</a>.
                    </label>
                </p>
                <button type="submit" class="submit-btn">Agree and Continue</button>
            </form>
        </section>
    </div>

    <footer>
        <p>&copy; 2024 [Your Company Name]. All rights reserved.</p>
    </footer>
</body>
</html>
